export const EDIT_EDITING = 'EDIT_EDITING';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const ADD_KEG = 'ADD_KEG';
export const DELETE_KEG = 'DELETE_KEG';
export const EDIT_SELECTEDKEG = 'EDIT_SELECTEDKEG';
export const SET_NULL_SELECTEDKEG = 'SET_NULL_SELECTEDKEG';
